### ISSUE TITLE
出现chrome不可用的错误。Message: unknown error: cannot connect to chrome at 127.0.0.1:50131 from chrome not reachable

### ISSUE THREAD

**Issue by neomx7** [slippersheepig/chatgpt-html#12]
我启动main的镜像，出现了以下错误，
（我进入镜像发现chrome是安装好的，不知道哪里出错了 ）

[2023-02-21 03:34:01 +0000] [118] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/chatgpt-html/main.py", line 12, in <module>
    chatbot = Chatbot(config)
              ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/Unofficial.py", line 72, in __init__
    self.__email_login()
  File "/usr/local/lib/python3.11/site-packages/revChatGPT/Unofficial.py", line 481, in __email_login
    driver = uc.Chrome(
             ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 441, in __init__
    super(Chrome, self).__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 80, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 104, in __init__
    super().__init__(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 704, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:50131
from chrome not reachable
Stacktrace:
#0 0x55d9dc042d93 <unknown>
#1 0x55d9dbe1115d <unknown>
#2 0x55d9dbdffa2b <unknown>
#3 0x55d9dbe3dc63 <unknown>
#4 0x55d9dbe352fc <unknown>
#5 0x55d9dbe7a4f4 <unknown>
#6 0x55d9dbe71353 <unknown>
#7 0x55d9dbe40e40 <unknown>
#8 0x55d9dbe42038 <unknown>
#9 0x55d9dc0968be <unknown>
#10 0x55d9dc09a8f0 <unknown>
#11 0x55d9dc07af90 <unknown>
#12 0x55d9dc09bb7d <unknown>
#13 0x55d9dc06c578 <unknown>
#14 0x55d9dc0c0348 <unknown>
#15 0x55d9dc0c04d6 <unknown>
#16 0x55d9dc0da341 <unknown>
#17 0x7f81c064fea7 start_thread

**Comment by slippersheepig** [comment]
刚用最新代码跑了一遍，重现了这个问题。应该是cloudflare那边patched了，作者项目主页和wiki也没有unofficial的使用方法了，仅仅代码里还有保留。感谢反馈，main分支已不可用。
