### ISSUE TITLE
2023-3-7版本，在amd64下闪跳

### ISSUE THREAD

**Issue by wudingjian** [slippersheepig/chatgpt-html#25]
2023-3-7版本，在amd64下闪跳

**Comment by slippersheepig** [comment]
国外鸡测试正常，贴上你的日志看看

**Comment by wudingjian** [comment]
我也是国外鸡

  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/chatgpt-html/main.py", line 8, in <module>
    with open("config.json", "r") as f: config = json.load(f)
                                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 9 (char 10)
[2023-03-07 12:51:16 +0000] [8] [INFO] Worker exiting (pid: 8)
[2023-03-07 12:51:16 +0000] [1] [INFO] Shutting down: Master
[2023-03-07 12:51:16 +0000] [1] [INFO] Reason: Worker failed to boot.
[2023-03-07 12:51:30 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-07 12:51:30 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
[2023-03-07 12:51:30 +0000] [1] [INFO] Using worker: gevent
[2023-03-07 12:51:30 +0000] [7] [INFO] Booting worker with pid: 7
[2023-03-07 12:51:30 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/chatgpt-html/main.py", line 8, in <module>
    with open("config.json", "r") as f: config = json.load(f)
                                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 9 (char 10)
[2023-03-07 12:51:30 +0000] [7] [INFO] Worker exiting (pid: 7)
[2023-03-07 12:51:30 +0000] [1] [INFO] Shutting down: Master
[2023-03-07 12:51:30 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by wudingjian** [comment]
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
&nbsp; &nbsp; self.load_wsgi()
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
&nbsp; &nbsp; self.wsgi = self.app.wsgi()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^^^^^^^^^^^^^^^
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
&nbsp; &nbsp; self.callable = self.load()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^^^^^^^^^^^
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
&nbsp; &nbsp; return self.load_wsgiapp()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
&nbsp; &nbsp; return util.import_app(self.app_uri)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
&nbsp; &nbsp; mod = importlib.import_module(module)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
&nbsp; &nbsp; return _bootstrap._gcd_import(name[level:], package, level)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "<frozen importlib._bootstrap&gt;", line 1206, in _gcd_import
&nbsp; File "<frozen importlib._bootstrap&gt;", line 1178, in _find_and_load
&nbsp; File "<frozen importlib._bootstrap&gt;", line 1149, in _find_and_load_unlocked
&nbsp; File "<frozen importlib._bootstrap&gt;", line 690, in _load_unlocked
&nbsp; File "<frozen importlib._bootstrap_external&gt;", line 940, in exec_module
&nbsp; File "<frozen importlib._bootstrap&gt;", line 241, in _call_with_frames_removed
&nbsp; File "/chatgpt-html/main.py", line 8, in <module&gt;
&nbsp; &nbsp; with open("config.json", "r") as f: config = json.load(f)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^
&nbsp; File "/usr/lib/python3.11/json/__init__.py", line 293, in load
&nbsp; &nbsp; return loads(fp.read(),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^
&nbsp; File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
&nbsp; &nbsp; return _default_decoder.decode(s)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
&nbsp; &nbsp; obj, end = self.raw_decode(s, idx=_w(s, 0).end())
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
&nbsp; &nbsp; obj, end = self.scan_once(s, idx)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 9 (char 10)
[2023-03-07 12:51:16 +0000] [8] [INFO] Worker exiting (pid: 8)
[2023-03-07 12:51:16 +0000] [1] [INFO] Shutting down: Master
[2023-03-07 12:51:16 +0000] [1] [INFO] Reason: Worker failed to boot.
[2023-03-07 12:51:30 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-07 12:51:30 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
[2023-03-07 12:51:30 +0000] [1] [INFO] Using worker: gevent
[2023-03-07 12:51:30 +0000] [7] [INFO] Booting worker with pid: 7
[2023-03-07 12:51:30 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
&nbsp; &nbsp; worker.init_process()
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
&nbsp; &nbsp; super().init_process()
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
&nbsp; &nbsp; self.load_wsgi()
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
&nbsp; &nbsp; self.wsgi = self.app.wsgi()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^^^^^^^^^^^^^^^
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
&nbsp; &nbsp; self.callable = self.load()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^^^^^^^^^^^
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
&nbsp; &nbsp; return self.load_wsgiapp()
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
&nbsp; &nbsp; return util.import_app(self.app_uri)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
&nbsp; &nbsp; mod = importlib.import_module(module)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
&nbsp; &nbsp; return _bootstrap._gcd_import(name[level:], package, level)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "<frozen importlib._bootstrap&gt;", line 1206, in _gcd_import
&nbsp; File "<frozen importlib._bootstrap&gt;", line 1178, in _find_and_load
&nbsp; File "<frozen importlib._bootstrap&gt;", line 1149, in _find_and_load_unlocked
&nbsp; File "<frozen importlib._bootstrap&gt;", line 690, in _load_unlocked
&nbsp; File "<frozen importlib._bootstrap_external&gt;", line 940, in exec_module
&nbsp; File "<frozen importlib._bootstrap&gt;", line 241, in _call_with_frames_removed
&nbsp; File "/chatgpt-html/main.py", line 8, in <module&gt;
&nbsp; &nbsp; with open("config.json", "r") as f: config = json.load(f)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^
&nbsp; File "/usr/lib/python3.11/json/__init__.py", line 293, in load
&nbsp; &nbsp; return loads(fp.read(),
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^
&nbsp; File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
&nbsp; &nbsp; return _default_decoder.decode(s)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
&nbsp; &nbsp; obj, end = self.raw_decode(s, idx=_w(s, 0).end())
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
&nbsp; File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
&nbsp; &nbsp; obj, end = self.scan_once(s, idx)
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 9 (char 10)
[2023-03-07 12:51:30 +0000] [7] [INFO] Worker exiting (pid: 7)
[2023-03-07 12:51:30 +0000] [1] [INFO] Shutting down: Master
[2023-03-07 12:51:30 +0000] [1] [INFO] Reason: Worker failed to boot.







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月7日(星期二) 晚上8:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [slippersheepig/chatgpt-html] 2023-3-7版本，在amd64下闪跳 (Issue #25)





 
国外鸡测试正常，贴上你的日志看看

**Comment by slippersheepig** [comment]
Expecting property name enclosed in double quotes: line 2 column 9 (char 10)
看看是不是config.json填写问题

**Comment by slippersheepig** [comment]
不客气，更新了一版config.json，应该可以避免此类问题了

**Comment by wudingjian** [comment]
请问一下，新版本config.json 如何注释不需要的行？

**Comment by slippersheepig** [comment]
> 请问一下，新版本config.json 如何注释不需要的行？

应该只需要填有用到的字段就行了，其他都不用改动
没用到的也可以全部删掉，不需要注释

**Comment by wudingjian** [comment]
更新到3-14版本后：
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 401, in __login
    auth.begin()
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 245, in __part_five
    self.__part_six(old_state=state, new_state=new_state)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 271, in __part_six
    self.__part_seven(redirect_url=redirect_url, previous_url=url)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 300, in __part_seven
    raise Error(
OpenAIAuth.Error
[2023-03-15 08:08:29 +0000] [7] [INFO] Worker exiting (pid: 7)
[2023-03-15 08:08:29 +0000] [1] [INFO] Shutting down: Master
[2023-03-15 08:08:29 +0000] [1] [INFO] Reason: Worker failed to boot.
[2023-03-15 08:08:55 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-15 08:08:55 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
[2023-03-15 08:08:55 +0000] [1] [INFO] Using worker: gevent
[2023-03-15 08:08:55 +0000] [7] [INFO] Booting worker with pid: 7
[2023-03-15 08:08:58 +0000] [7] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/chatgpt-html/main.py", line 11, in <module>
    chatbot = Chatbot(config)
              ^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 233, in __init__
    self.__check_credentials()
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 258, in __check_credentials
    raise error
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 256, in __check_credentials
    self.__login()
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 401, in __login
    auth.begin()
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 76, in begin
    self.__part_one(token=csrf_token)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 117, in __part_one
    self.__part_two(url=url)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 146, in __part_two
    self.__part_three(state=state)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 170, in __part_three
    self.__part_four(state=state)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 208, in __part_four
    self.__part_five(state=state)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 245, in __part_five
    self.__part_six(old_state=state, new_state=new_state)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 271, in __part_six
    self.__part_seven(redirect_url=redirect_url, previous_url=url)
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 300, in __part_seven
    raise Error(
OpenAIAuth.Error
[2023-03-15 08:08:58 +0000] [7] [INFO] Worker exiting (pid: 7)
[2023-03-15 08:08:58 +0000] [1] [INFO] Shutting down: Master
[2023-03-15 08:08:58 +0000] [1] [INFO] Reason: Worker failed to boot.

其他配置啥的都没有变，不知哪里报错了？

**Comment by wudingjian** [comment]
感觉应该是账号，登陆失败。

**Comment by slippersheepig** [comment]
今天开始有大批账号被封，确切原因暂未明了，但作者认为基本是因为用了[V1](https://github.com/acheong08/ChatGPT/issues/1158)，建议暂时先不要使用我的项目
