### ISSUE TITLE
worker fail to boot

### ISSUE THREAD

**Issue by ydqsbfsyi** [slippersheepig/chatgpt-html#29]
装在了vps上，网页不通。 用portainer观察，container貌似在运行，但log说：

> json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
[2023-03-11 14:40:22 +0000] [6] [INFO] Worker exiting (pid: 6)
[2023-03-11 14:40:23 +0000] [1] [INFO] Shutting down: Master
[2023-03-11 14:40:23 +0000] [1] [INFO] Reason: Worker failed to boot.
[2023-03-11 14:41:25 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-11 14:41:25 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
[2023-03-11 14:41:25 +0000] [1] [INFO] Using worker: gevent
[2023-03-11 14:41:25 +0000] [6] [INFO] Booting worker with pid: 6
[2023-03-11 14:41:26 +0000] [6] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/chatgpt-html/main.py", line 8, in <module>
    with open("config.json", "r") as f: config = json.load(f)
                                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
[2023-03-11 14:41:26 +0000] [6] [INFO] Worker exiting (pid: 6)
[2023-03-11 14:41:27 +0000] [1] [INFO] Shutting down: Master
[2023-03-11 14:41:27 +0000] [1] [INFO] Reason: Worker failed to boot.
[2023-03-11 14:42:29 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-11 14:42:29 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
[2023-03-11 14:42:29 +0000] [1] [INFO] Using worker: gevent
[2023-03-11 14:42:29 +0000] [6] [INFO] Booting worker with pid: 6
[2023-03-11 14:42:31 +0000] [6] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/chatgpt-html/main.py", line 8, in <module>
    with open("config.json", "r") as f: config = json.load(f)
                                                 ^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/__init__.py", line 335, in loads
    raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
[2023-03-11 14:42:31 +0000] [6] [INFO] Worker exiting (pid: 6)
[2023-03-11 14:42:31 +0000] [1] [INFO] Shutting down: Master
[2023-03-11 14:42:31 +0000] [1] [INFO] Reason: Worker failed to boot.

**Comment by slippersheepig** [comment]
raise JSONDecodeError("Unexpected UTF-8 BOM (decode using utf-8-sig)",
json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
外部编辑器保存时注意格式，不要有BOM等额外属性

**Comment by ydqsbfsyi** [comment]
谢谢。 
记得一开始我可能用的是ANSI，提示一个错误，utf8什么的，我就改存为UTF8了。

刚刚从新改存为unicode，重新部署，然后：

>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/chatgpt-html/main.py", line 8, in <module>
    with open("config.json", "r") as f: config = json.load(f)
         ^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'config.json'
[2023-03-12 02:27:07 +0000] [6] [INFO] Worker exiting (pid: 6)
[2023-03-12 02:27:08 +0000] [1] [INFO] Shutting down: Master
[2023-03-12 02:27:08 +0000] [1] [INFO] Reason: Worker failed to boot.
[2023-03-12 02:27:20 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-12 02:27:20 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
[2023-03-12 02:27:20 +0000] [1] [INFO] Using worker: gevent
[2023-03-12 02:27:20 +0000] [6] [INFO] Booting worker with pid: 6
[2023-03-12 02:27:21 +0000] [6] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/chatgpt-html/main.py", line 8, in <module>
    with open("config.json", "r") as f: config = json.load(f)
         ^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'config.json'
[2023-03-12 02:27:21 +0000] [6] [INFO] Worker exiting (pid: 6)
[2023-03-12 02:27:22 +0000] [1] [INFO] Shutting down: Master
[2023-03-12 02:27:22 +0000] [1] [INFO] Reason: Worker failed to boot.
[2023-03-12 02:27:33 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2023-03-12 02:27:33 +0000] [1] [INFO] Listening at: http://0.0.0.0:8088 (1)
[2023-03-12 02:27:33 +0000] [1] [INFO] Using worker: gevent
[2023-03-12 02:27:33 +0000] [6] [INFO] Booting worker with pid: 6
[2023-03-12 02:27:34 +0000] [6] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/chatgpt-html/main.py", line 8, in <module>
    with open("config.json", "r") as f: config = json.load(f)
         ^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: 'config.json'
[2023-03-12 02:27:34 +0000] [6] [INFO] Worker exiting (pid: 6)
[2023-03-12 02:27:35 +0000] [1] [INFO] Shutting down: Master
[2023-03-12 02:27:35 +0000] [1] [INFO] Reason: Worker failed to boot.
