### ISSUE TITLE
HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe837958150>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

### ISSUE THREAD

**Issue by hanbingxzy** [slippersheepig/chatgpt-html#30]
提问后返回异常
HTTPSConnectionPool(host='chatgpt.duti.tech', port=443): Max retries exceeded with url: /api/conversation (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe837958150>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

**Comment by slippersheepig** [comment]
用新镜像，proxy版默认的作者代理地址已经没了
或者`docker-compose.yml`补充`CHATGPT_BASE_URL=https://gpt.pawan.krd/backend-api/`试试

**Comment by hanbingxzy** [comment]
似乎还是不行
用新镜像报 RuntimeError: can't start new thread
使用 proxy 和 CHATGPT_BASE_URL=https://gpt.pawan.krd/backend-api/ 无返回，后台日志打印了一大段 html

**Comment by slippersheepig** [comment]
> 似乎还是不行 用新镜像报 RuntimeError: can't start new thread 使用 proxy 和 CHATGPT_BASE_URL=https://gpt.pawan.krd/backend-api/ 无返回，后台日志打印了一大段 html

新镜像再用`CHATGPT_BASE_URL=https://gpt.pawan.krd/backend-api/`，刚我测试是可以的
如果还是有问题，那可能是你的网络问题，不好排查

**Comment by hanbingxzy** [comment]
新镜像加环境变量还是不行

镜像已最新
docker.io/sheepgreen/chatgpt-html                      latest                       9e41a70701ae        2 days ago          1.14 GB

这是我的启动命令
 docker run -d  --name=chatgpthtml -v /root/pvc/config.json:/chatgpt-html/config.json -e CHATGPT_BASE_URL=https://gpt.pawan.krd/backend-api/ sheepgreen/chatgpt-html:latest

使用session_token 启动报错 can't start new thread
使用 access_token 能启动，但一查询也报 can't start new thread

会是因为香港服务器的关系吗？

**Comment by hanbingxzy** [comment]
[2023-03-12 09:56:19 +0000] [6] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/ggevent.py", line 146, in init_process
    super().init_process()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/chatgpt-html/main.py", line 11, in <module>
    chatbot = Chatbot(config)
              ^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 233, in __init__
    self.__check_credentials()
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 256, in __check_credentials
    self.__login()
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 58, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/revChatGPT/V1.py", line 394, in __login
    auth.get_access_token()
  File "/home/appuser/.local/lib/python3.11/site-packages/OpenAIAuth.py", line 314, in get_access_token
    response = self.session.get(
               ^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/appuser/.local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/appuser/.local/lib/python3.11/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gevent/_socketcommon.py", line 247, in getaddrinfo
    addrlist = get_hub().resolver.getaddrinfo(host, port, family, type, proto, flags)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gevent/resolver/thread.py", line 63, in getaddrinfo
    return self.pool.apply(_socket.getaddrinfo, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gevent/pool.py", line 161, in apply
    return self.spawn(func, *args, **kwds).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/appuser/.local/lib/python3.11/site-packages/gevent/threadpool.py", line 546, in spawn
    self.adjust()
  File "/home/appuser/.local/lib/python3.11/site-packages/gevent/threadpool.py", line 492, in adjust
    self._adjust_step()
  File "/home/appuser/.local/lib/python3.11/site-packages/gevent/threadpool.py", line 472, in _adjust_step
    self._add_thread()
  File "/home/appuser/.local/lib/python3.11/site-packages/gevent/threadpool.py", line 499, in _add_thread
    self._WorkerGreenlet(self)
  File "/home/appuser/.local/lib/python3.11/site-packages/gevent/threadpool.py", line 106, in __init__
    start_new_thread(self._begin, ())
RuntimeError: can't start new thread

**Comment by slippersheepig** [comment]
> 会是因为香港服务器的关系吗？

[OPENAI支持的国家和地区](https://platform.openai.com/docs/supported-countries)，香港目前不在支持范围内
